/* Auto-generated by generate_data.py — do not edit by hand. */
window.RAKA_DATA = {
  "projects": [
    {
      "slug": "saras-co",
      "title": "Saras Co",
      "year": "2024",
      "role": "Brand identity & visual language",
      "descriptor": "A Bombay music & events company touring world-class live acts across India.",
      "intro": "When we set out to build Saras Co's identity, one thing mattered above all: a mark that is memorable, robust and built to last — one that scales and travels across any medium effortlessly. The answer drew on iconic 80s record-label iconography and a brutalist edge.",
      "slides": [
        {
          "src": "assets/projects/saras-co/01.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The core logo unit — a mark that reads at once as a tape reel, a disc, and the Gujarati hand-gesture for 'good.' In Gujarati, saras means something genuinely cool."
        },
        {
          "src": "assets/projects/saras-co/02.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The tagline in use: In Good Company. When the room is full of world-class touring artists and an audience that truly listens, you're in good company."
        },
        {
          "src": "assets/projects/saras-co/03.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The wordmark — drawn from the masthead of Gujarat Samachar and rebuilt letter by letter in English, custom-illustrated to sit between 80s record label and brutalist."
        },
        {
          "src": "assets/projects/saras-co/04.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The identity on apparel — the mark holds its punch from a tee to a tote."
        },
        {
          "src": "assets/projects/saras-co/05.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Merch carries the same robust mark across cream and black."
        },
        {
          "src": "assets/projects/saras-co/06.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Across posters and social the language stays consistent — timeless yet contemporary, vintage nostalgia tuned to today's musical landscape."
        },
        {
          "src": "assets/projects/saras-co/07.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The final wordmark: striking, scalable, and built to last."
        }
      ]
    },
    {
      "slug": "unboxing-blr",
      "title": "Unboxing BLR",
      "year": "2024",
      "role": "Brand guidelines & identity system",
      "descriptor": "A participative, volunteer-driven project crafting a new brand narrative for Bangalore.",
      "intro": "Bangalore has quietly become a multifaceted global city, yet its story has never been told as well as it deserves. Unboxing BLR is a volunteer-driven effort to craft that narrative across many media — and this is the identity system that holds it all together.",
      "slides": [
        {
          "src": "assets/projects/unboxing-blr/01.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Brand guidelines for Unboxing BLR — a volunteer-driven project crafting a new narrative for Bangalore across many media."
        },
        {
          "src": "assets/projects/unboxing-blr/02.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The purpose: hand the brand to every stakeholder, so the identity stays consistent wherever it appears."
        },
        {
          "src": "assets/projects/unboxing-blr/03.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Vis-à-vis its past, Bangalore has grown into a multifaceted global city — a story that deserves to be articulated better. That's the brief."
        },
        {
          "src": "assets/projects/unboxing-blr/04.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The logo."
        },
        {
          "src": "assets/projects/unboxing-blr/05.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The wordmark reads as unboxingBLR — U caps, nboxing lower, BLR all caps — paired with the line The City of New Beginnings."
        },
        {
          "src": "assets/projects/unboxing-blr/06.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The palette shifts to a vibrant red and yellow drawn from the state flag, tying the brand to the city; the heart returns to a single colour to stay legible when scaled down."
        },
        {
          "src": "assets/projects/unboxing-blr/07.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Do: hold the identity against white or off-white, where it has strong contrast."
        },
        {
          "src": "assets/projects/unboxing-blr/08.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Don't: drop it onto busy textures or low-contrast colour that kills the mark."
        },
        {
          "src": "assets/projects/unboxing-blr/09.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Lockups for print, web and mobile — including a condensed heart-and-BLR mark and a co-brand lock-up with Bangalore International Centre."
        },
        {
          "src": "assets/projects/unboxing-blr/10.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Typography: Titillium — tall, lightly rounded, structurally robust — as the primary face, set alongside Kannada for the city it speaks to."
        },
        {
          "src": "assets/projects/unboxing-blr/11.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The heart becomes a system — icons for conversation, collaboration, foresight, heritage, technology and hospitality, and a pattern built from the unboxed heart."
        },
        {
          "src": "assets/projects/unboxing-blr/12.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Two palettes: a primary that reads as the city's drive and optimism, and a secondary for its landscape, culture and tech."
        },
        {
          "src": "assets/projects/unboxing-blr/13.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Imagery."
        },
        {
          "src": "assets/projects/unboxing-blr/14.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Diverse, energetic, evergreen, effortlessly cool — the city in its own script."
        },
        {
          "src": "assets/projects/unboxing-blr/15.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The city where the future is built. The city of now."
        },
        {
          "src": "assets/projects/unboxing-blr/16.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The city of diverse cultures — heritage and everyday Bangalore, side by side."
        },
        {
          "src": "assets/projects/unboxing-blr/17.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Great conversations. Even better ideas."
        },
        {
          "src": "assets/projects/unboxing-blr/18.jpg",
          "w": 1366,
          "h": 967,
          "caption": "True Southern hospitality. Like no other."
        },
        {
          "src": "assets/projects/unboxing-blr/19.jpg",
          "w": 1366,
          "h": 967,
          "caption": "The identity worn — apparel that lets people carry the city's story."
        },
        {
          "src": "assets/projects/unboxing-blr/20.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Tote lock-ups in English and Kannada — compact and instantly recognisable."
        },
        {
          "src": "assets/projects/unboxing-blr/21.jpg",
          "w": 1366,
          "h": 967,
          "caption": "Logo behaviour for video — over imagery, at 20% opacity, in solid zaffre, and in black."
        },
        {
          "src": "assets/projects/unboxing-blr/22.jpg",
          "w": 1366,
          "h": 967,
          "caption": "♥BLR. Fin."
        }
      ]
    }
  ],
  "posters": [
    {
      "slug": "joe-armon-jones-tour-png",
      "title": "Joe Armon Jones",
      "caption": "Bringing Joe Armon Jones to India for the first time, presented by Saras — Bangalore and Mumbai.",
      "thumb": "assets/posters/thumb/joe-armon-jones-tour-png.jpg",
      "full": "assets/posters/full/joe-armon-jones-tour-png.jpg",
      "w": 1060,
      "h": 1500
    },
    {
      "slug": "akbars-court-a4",
      "title": "Akbar's Court",
      "caption": "An event series by Mumbai's Nrtya — a quirky, contemporary take on Mughal-court art, with Arteramesh, Tansane, Nigel, Rajaratnam and Capricio.",
      "thumb": "assets/posters/thumb/akbars-court-a4.jpg",
      "full": "assets/posters/full/akbars-court-a4.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "di-web-flyer",
      "title": "Dualist Inquiry",
      "caption": "Delhi's Dualist Inquiry guards his privacy, so the brief was to never show his face directly — only manipulate it with texture. Which is exactly what happened.",
      "thumb": "assets/posters/thumb/di-web-flyer.jpg",
      "full": "assets/posters/full/di-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "kahn-a4",
      "title": "Kahn",
      "caption": "With Krunk, for their 8th anniversary — Kahn from the UK and his deep, grimy, thunderous dubstep. 18–20 May 2017.",
      "thumb": "assets/posters/thumb/kahn-a4.jpg",
      "full": "assets/posters/full/kahn-a4.jpg",
      "w": 1001,
      "h": 1500
    },
    {
      "slug": "teklife-tour-bangalore",
      "title": "Teklife",
      "caption": "DJs from the Teklife crew — originators of footwork, a genre that has gone global from the US and UK to Southeast Asia, Australia and Japan. Bangalore.",
      "thumb": "assets/posters/thumb/teklife-tour-bangalore.jpg",
      "full": "assets/posters/full/teklife-tour-bangalore.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "ripple-2x3f",
      "title": "Ripple",
      "caption": "Oceantied's club-night series, Ripple — inspired by early-2000s UK rave flyers crossed with science fiction.",
      "thumb": "assets/posters/thumb/ripple-2x3f.jpg",
      "full": "assets/posters/full/ripple-2x3f.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "loefah-a4",
      "title": "Loefah",
      "caption": "Loefah's India tour as part of Bassick Sense, with Oceantied on support.",
      "thumb": "assets/posters/thumb/loefah-a4.jpg",
      "full": "assets/posters/full/loefah-a4.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "bassick-sense-del-vol-11-flyer",
      "title": "Bassick Sense Vol. 11",
      "caption": "Bassick Sense, an IP I co-created with Social in 2016 — a rootsy, contemporary look held across the whole series. Delhi.",
      "thumb": "assets/posters/thumb/bassick-sense-del-vol-11-flyer.jpg",
      "full": "assets/posters/full/bassick-sense-del-vol-11-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "malfnktion-a3",
      "title": "Malfnktion",
      "caption": "Malfnktion, framed by the analog and MIDI gear he surrounds himself with.",
      "thumb": "assets/posters/thumb/malfnktion-a3.jpg",
      "full": "assets/posters/full/malfnktion-a3.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "oceantied-a3-print",
      "title": "Oceantied — Euro Tour",
      "caption": "Oceantied's European tour — Prague, Malta, Finland, Croatia — plus festivals like Outlook and Dimensions.",
      "thumb": "assets/posters/thumb/oceantied-a3-print.jpg",
      "full": "assets/posters/full/oceantied-a3-print.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "su-real-niki-web-flyer",
      "title": "Su Real × Niki",
      "caption": "The very first poster with Krunk — Delhi's Su Real featuring Niki, at Bonobo, Bombay. Minimal type over the artist's portrait.",
      "thumb": "assets/posters/thumb/su-real-niki-web-flyer.jpg",
      "full": "assets/posters/full/su-real-niki-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "taaq-1",
      "title": "Thermal And A Quarter",
      "caption": "Thermal And A Quarter, hosted by The Humming Tree. The name hides a pun few catch — three malus and a quarter malo; the band began as four.",
      "thumb": "assets/posters/thumb/taaq-1.jpg",
      "full": "assets/posters/full/taaq-1.jpg",
      "w": 1060,
      "h": 1500
    },
    {
      "slug": "bombay-bandstand-print-2x3",
      "title": "Bombay Bandstand",
      "caption": "For Social's Bombay Bandstand — an IP built around live musicians and live music.",
      "thumb": "assets/posters/thumb/bombay-bandstand-print-2x3.jpg",
      "full": "assets/posters/full/bombay-bandstand-print-2x3.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "barely-legal-tour-web-flyer-delhi",
      "title": "Barely Legal",
      "caption": "For Chloe Robinson (formerly Barely Legal) — the Delhi date of the India tour.",
      "thumb": "assets/posters/thumb/barely-legal-tour-web-flyer-delhi.jpg",
      "full": "assets/posters/full/barely-legal-tour-web-flyer-delhi.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "aj-saras-poster",
      "title": "Alicia Joy × Saras",
      "caption": "A tour poster for Alicia Joy's India run with Krunk and Saras — Delhi, Mumbai, Kolkata and Goa. 2025.",
      "thumb": "assets/posters/thumb/aj-saras-poster.jpg",
      "full": "assets/posters/full/aj-saras-poster.jpg",
      "w": 1080,
      "h": 1500
    },
    {
      "slug": "jaj-main-tour-print",
      "title": "Joe Armon Jones",
      "caption": "The main tour print for Joe Armon Jones' first India run with Saras.",
      "thumb": "assets/posters/thumb/jaj-main-tour-print.jpg",
      "full": "assets/posters/full/jaj-main-tour-print.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "spaven-tour-2-main",
      "title": "Richard Spaven",
      "caption": "Richard Spaven's second India tour — Mumbai, Dubai and Goa. Built from a cinematic montage of on-stage portraits.",
      "thumb": "assets/posters/thumb/spaven-tour-2-main.jpg",
      "full": "assets/posters/full/spaven-tour-2-main.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "mocity-tbone-stakez-web-flyer",
      "title": "MoCity × T-Bone Stakez",
      "caption": "Two gun-fingers and directional arrows. Fri 6 Jan, 10pm, Mumbai.",
      "thumb": "assets/posters/thumb/mocity-tbone-stakez-web-flyer.jpg",
      "full": "assets/posters/full/mocity-tbone-stakez-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "ez-riser-oceantied-a4-web-flyer",
      "title": "EZ Riser × Oceantied",
      "caption": "With Krunk — bringing the contemporary poster language of UK and European electronic events to the Indian scene.",
      "thumb": "assets/posters/thumb/ez-riser-oceantied-a4-web-flyer.jpg",
      "full": "assets/posters/full/ez-riser-oceantied-a4-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "raji-rags-print",
      "title": "Raji Rags",
      "caption": "A Boiler Room / NTS Radio name at Bangalore Social — 12 Jan 2017.",
      "thumb": "assets/posters/thumb/raji-rags-print.jpg",
      "full": "assets/posters/full/raji-rags-print.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "bliss",
      "title": "Bliss",
      "caption": null,
      "thumb": "assets/posters/thumb/bliss.jpg",
      "full": "assets/posters/full/bliss.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "blot-zokhuma-web-flyer",
      "title": "Blot × Zokhuma",
      "caption": null,
      "thumb": "assets/posters/thumb/blot-zokhuma-web-flyer.jpg",
      "full": "assets/posters/full/blot-zokhuma-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "ez-riser-tansane-web-flyer",
      "title": "EZ Riser × Tansane",
      "caption": "With Krunk — EZ Riser and Tansane, Mumbai.",
      "thumb": "assets/posters/thumb/ez-riser-tansane-web-flyer.jpg",
      "full": "assets/posters/full/ez-riser-tansane-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "goth-trad-a4",
      "title": "Goth-Trad",
      "caption": null,
      "thumb": "assets/posters/thumb/goth-trad-a4.jpg",
      "full": "assets/posters/full/goth-trad-a4.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "iseo-dodosound-flyer",
      "title": "Iseo & Dodosound",
      "caption": null,
      "thumb": "assets/posters/thumb/iseo-dodosound-flyer.jpg",
      "full": "assets/posters/full/iseo-dodosound-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "madboy-a4",
      "title": "Madboy A4",
      "caption": null,
      "thumb": "assets/posters/thumb/madboy-a4.jpg",
      "full": "assets/posters/full/madboy-a4.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "oceantied-euro-tour-2-pdf-a4",
      "title": "Oceantied — Euro Tour",
      "caption": "Oceantied across Europe — the second run.",
      "thumb": "assets/posters/thumb/oceantied-euro-tour-2-pdf-a4.jpg",
      "full": "assets/posters/full/oceantied-euro-tour-2-pdf-a4.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "oceantied-ez-riser-malta-web-flyer",
      "title": "Oceantied × EZ Riser — Malta",
      "caption": null,
      "thumb": "assets/posters/thumb/oceantied-ez-riser-malta-web-flyer.jpg",
      "full": "assets/posters/full/oceantied-ez-riser-malta-web-flyer.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "oceantied-x-ez-a4",
      "title": "Oceantied × EZ Riser",
      "caption": null,
      "thumb": "assets/posters/thumb/oceantied-x-ez-a4.jpg",
      "full": "assets/posters/full/oceantied-x-ez-a4.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "ox7gen-ezriser",
      "title": "Ox7gen × EZ Riser",
      "caption": null,
      "thumb": "assets/posters/thumb/ox7gen-ezriser.jpg",
      "full": "assets/posters/full/ox7gen-ezriser.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "pxo-web-flyer",
      "title": "PxO",
      "caption": null,
      "thumb": "assets/posters/thumb/pxo-web-flyer.jpg",
      "full": "assets/posters/full/pxo-web-flyer.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "ra-flyer",
      "title": "RA",
      "caption": null,
      "thumb": "assets/posters/thumb/ra-flyer.jpg",
      "full": "assets/posters/full/ra-flyer.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "saras-curations-story",
      "title": "Saras Curations",
      "caption": null,
      "thumb": "assets/posters/thumb/saras-curations-story.jpg",
      "full": "assets/posters/full/saras-curations-story.jpg",
      "w": 818,
      "h": 1500
    },
    {
      "slug": "saras-curations-unit-red",
      "title": "Saras Curations",
      "caption": null,
      "thumb": "assets/posters/thumb/saras-curations-unit-red.jpg",
      "full": "assets/posters/full/saras-curations-unit-red.jpg",
      "w": 1200,
      "h": 1500
    },
    {
      "slug": "saras-spaven-3-2",
      "title": "Saras × Spaven",
      "caption": null,
      "thumb": "assets/posters/thumb/saras-spaven-3-2.jpg",
      "full": "assets/posters/full/saras-spaven-3-2.jpg",
      "w": 1117,
      "h": 1500
    },
    {
      "slug": "sphaira-a3-print",
      "title": "Sphaira",
      "caption": null,
      "thumb": "assets/posters/thumb/sphaira-a3-print.jpg",
      "full": "assets/posters/full/sphaira-a3-print.jpg",
      "w": 1061,
      "h": 1500
    },
    {
      "slug": "sputnik-a3-print",
      "title": "Sputnik",
      "caption": "A personal experiment — not a gig poster — a play on the elements of nature, like the wind.",
      "thumb": "assets/posters/thumb/sputnik-a3-print.jpg",
      "full": "assets/posters/full/sputnik-a3-print.jpg",
      "w": 1000,
      "h": 1500
    },
    {
      "slug": "tamypro-dansun-web-flyer-2",
      "title": "Tamypro × DanSun",
      "caption": null,
      "thumb": "assets/posters/thumb/tamypro-dansun-web-flyer-2.jpg",
      "full": "assets/posters/full/tamypro-dansun-web-flyer-2.jpg",
      "w": 1061,
      "h": 1500
    }
  ]
};
